spring.datasource.url=jdbc:mysql://localhost:3306/fooddb
spring.datasource.username=root
spring.datasource.password=Keerthi@1734

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085